import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { experiments, labPeople, apparatus } from './data.js';
import './style.css';

const app=document.querySelector('#app');
const perf=document.querySelector('#perf');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function fail(e){console.error(e);const boot=document.querySelector('#boot');if(boot)boot.style.display='none';const f=document.querySelector('#fallback');if(f){f.style.display='grid';f.innerHTML='<div><h2>⚠️ ScienceVerse could not start</h2><p class="muted">The 3D engine reported an error. Tap Retry to try again.</p><button onclick="location.reload()">Retry</button><p class="muted" style="margin-top:12px">'+esc(e?.message||'Unknown error')+'</p></div>';}}

try{
app.innerHTML=`<div id="scene"></div><div class="hud"><header><div class="brand">🧪 <b>Science</b>Verse <small>3D LAB</small></div><div id="perf">● STARTING</div></header><div class="desktopPanels"><section class="panel left"><h4>LABS</h4><button data-lab="chem">🧪 Chemistry</button><button data-lab="phys">⚡ Physics</button><button data-lab="bio">🧬 Biology</button><button data-lab="space">🚀 Space Lab</button><button id="peopleBtn">👥 People</button></section><section class="panel right"><h4>EXPERIMENT</h4><select id="class"></select><div id="expList"></div><button id="selfBtn" class="primary">🧠 Self Experiment</button></section></div><div class="bottom"><button id="expBtn">🧪 Experiments</button><button id="toolsBtn">🧰 Equipment</button><button id="assistantBtn">🤖 Assistant</button><button id="reportBtn">📊 Lab Report</button></div><div id="sheet" class="sheet"></div><div class="look">☝️ Drag = look • 🤏 Pinch = zoom</div></div>`;

const sceneEl=document.querySelector('#scene');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x061018);scene.fog=new THREE.Fog(0x061018,22,55);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.05,140);camera.position.set(10,6,12);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.25));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;sceneEl.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=4;controls.maxDistance=38;controls.maxPolarAngle=Math.PI*.49;controls.target.set(0,2,0);
const balls=[],results=[];const clock=new THREE.Clock();
const mat=(c,r=.55,m=.08)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
function box(n,x,y,z,w,h,d,c){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));o.name=n;o.position.set(x,y,z);scene.add(o);return o;}
function cyl(n,x,y,z,r,h,c){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),mat(c,.35));o.name=n;o.position.set(x,y,z);scene.add(o);return o;}
function ball(n,x,y,z,r,c){const o=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),mat(c,.35));o.name=n;o.position.set(x,y,z);scene.add(o);return o;}
function label(t){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#081722';x.roundRect(8,8,496,112,22);x.fill();x.fillStyle='#dff9ff';x.font='bold 38px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(t,256,64);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true}));s.scale.set(3.2,.8,1);return s;}
function world(){scene.add(new THREE.HemisphereLight(0xbfeaff,0x16202a,2));const k=new THREE.DirectionalLight(0xffffff,2.2);k.position.set(8,13,7);scene.add(k);box('Floor',0,-.25,0,32,.5,24,0x1a252a);box('BackWall',0,5,-11,32,10,.3,0x14252c);box('LeftWall',-16,5,0,.3,10,22,0x122128);box('RightWall',16,5,0,.3,10,22,0x122128);
for(let x=-12;x<=12;x+=6){box('Bench',x,1.45,-2,5.2,.45,3.3,0x6c7478);box('Shelf',x,3.3,-3.35,4.8,2.3,.22,0x26383f);}for(const [n,x,c] of [['CHEMISTRY',-9,0x2f6672],['PHYSICS',3,0x4c536d],['BIOLOGY',-3,0x466e58],['SPACE',9,0x5b4d78]]){const s=label(n);s.position.set(x,5.2,-3.4);scene.add(s);box('station',x,.15,-7,5,.2,1,c);}
for(let x=-11;x<=-7;x+=2){cyl('Beaker',x,2.05,-2,.38,.8,0x72dfff);cyl('Flask',x+.7,2.05,-2,.46,.7,0x72d0bd);}box('Track',2,1.93,-2,6,.1,.45,0x3f474d);box('Cart',1,2.3,-2,.9,.5,.75,0xd95252);ball('Wheel',.72,2.03,-2.36,.16,0x17191b);ball('Wheel',1.28,2.03,-2.36,.16,0x17191b);box('Meter',4,2.25,-2,1.1,.65,.55,0x203d4c);box('PendulumStand',6,3.3,-2,.15,3.2,.15,0xbcc6ca);ball('PendulumBob',6,1.9,-2,.34,0xff5368);
cyl('Microscope',-4.5,2.3,1.8,.45,1.7,0x89969b);cyl('Centrifuge',-2.2,2,1.8,.7,.55,0x59686e);box('PCR',-4,2,4,1.6,.9,1.1,0x344c55);box('BioBench',-1,1.45,2.8,6,.45,2.5,0x657277);box('SpaceBench',9,1.45,2.8,6,.45,2.5,0x535b66);cyl('RocketBody',9,3.4,2.8,.45,2.8,0xd9dce0);cyl('RocketNose',9,5.05,2.8,.45,.55,0xff5a62);box('FinL',8.55,2.65,2.8,.18,.7,.75,0xff6b4d);box('FinR',9.45,2.65,2.8,.18,.7,.75,0xff6b4d);
for(let i=0;i<9;i++){const a=i*Math.PI*2/9;ball('Atom',12+Math.cos(a)*1.3,3.7+Math.sin(a)*.9,3,.25,i%3===0?0xff5b6e:0x56d8ff);}labPeople.forEach((p,i)=>npc(p,-12+i*4,1+i%2*2));}
function npc(p,x,z){const g=new THREE.Group();g.position.set(x,0,z);const m=mat(0x405a78);const t=new THREE.Mesh(new THREE.CapsuleGeometry(.32,.9,4,8),m);t.position.y=1.15;g.add(t);const h=new THREE.Mesh(new THREE.SphereGeometry(.28,12,10),mat(0xf1c5a8));h.position.y=1.9;g.add(h);const l=label(p[1]);l.scale.set(2,.5,1);l.position.y=2.55;g.add(l);g.userData.phase=x;scene.add(g);}
function sheet(html){const s=document.querySelector('#sheet');s.innerHTML='<div class="sheetHead"><button id="close">✕</button></div>'+html;s.classList.add('open');document.querySelector('#close').onclick=()=>s.classList.remove('open');}
function close(){document.querySelector('#sheet').classList.remove('open');}
function labs(){document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>teleport(b.dataset.lab));}
function teleport(w){const p=({chem:[-9,4,8],phys:[3,4,8],bio:[-3,4,10],space:[9,4,10]})[w]||[0,4,8];controls.target.set(...p);camera.position.set(p[0]+7,p[1]+2,p[2]+7);close();}
function classes(){const s=document.querySelector('#class');Object.keys(experiments).forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=k==='12+'?'Class 12+':'Class '+k;s.appendChild(o)});s.value='12';renderExps();s.onchange=renderExps;}
function renderExps(){const cls=document.querySelector('#class').value;const list=document.querySelector('#expList');list.innerHTML=(experiments[cls]||[]).map(e=>`<button class="exp" data-e="${esc(e)}"><b>${esc(e)}</b><small>Interactive practical • observe • measure • explain</small></button>`).join('');list.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>experiment(b.dataset.e,cls));}
function experiment(n,c){sheet(`<h3>🧪 ${esc(n)}</h3><p>Class ${c} — learn it by doing it.</p><div class="steps"><b>Aim</b><span>Find the question and variables.</span><b>Apparatus</b><span>Choose the equipment yourself.</span><b>Perform</b><span>Change variables and run the simulation.</span><b>Observe</b><span>Record measurements.</span><b>Explain</b><span>Connect the observation to the science.</span></div><button class="primary" id="enter">▶ Enter Experiment</button>`);document.querySelector('#enter').onclick=()=>{close();const q=n.toLowerCase();teleport(q.includes('projectile')||q.includes('ohm')||q.includes('resistance')?'phys':q.includes('pcr')||q.includes('cell')||q.includes('dna')?'bio':q.includes('rocket')?'space':'chem');};}
function tools(){sheet(`<h3>🧰 Equipment Locker</h3><div class="toolgrid">${apparatus.map(a=>`<button data-t="${esc(a)}">${esc(a)}</button>`).join('')}</div>`);document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{spawn(b.dataset.t);close();});}
function spawn(t){const q=t.toLowerCase();if(q.includes('ball'))ball('YourBall',0,3,-1,.32,0xff4f64);else if(q.includes('battery')){box('Battery',0,2.5,-1,.7,.8,.7,0x202b35);box('Plus',-.18,2.95,-1,.12,.08,.12,0xff5a5a);box('Minus',.18,2.95,-1,.12,.08,.12,0x55baff);}else if(q.includes('beaker'))cyl('YourBeaker',0,2.25,-1,.4,.8,0x65dfff);else box(t,0,2.4,-1,.8,.8,.8,0x718087);}
function self(){sheet(`<h3>🧠 Self Experiment</h3><p>Change variables and test your own idea.</p><label>Speed <output id="so">12</output> m/s</label><input id="speed" type="range" min="1" max="30" value="12"><label>Angle <output id="ao">45</output>°</label><input id="angle" type="range" min="5" max="85" value="45"><label>Gravity <output id="go">9.81</output> m/s²</label><input id="gravity" type="range" min="1" max="20" step=".01" value="9.81"><button class="primary" id="throw">🚀 Throw Ball</button><div id="physicsOut" class="answer">Run a trial to see the measurements.</div>`);for(const [id,out] of [['speed','so'],['angle','ao'],['gravity','go']])document.querySelector('#'+id).oninput=e=>document.querySelector('#'+out).value=e.target.value;document.querySelector('#throw').onclick=()=>throwIt(+speed.value,+angle.value,+gravity.value);}
function throwIt(v,a,g){const r=v*v*Math.sin(2*a*Math.PI/180)/g,h=.5+v*v*Math.sin(a*Math.PI/180)**2/(2*g),time=2*v*Math.sin(a*Math.PI/180)/g;const o=ball('ThrownBall',0,.5,0,.28,0xff465e);balls.push({o,t:0,v,a:a*Math.PI/180,g,time});results.push(`Projectile: ${r.toFixed(2)} m range; ${h.toFixed(2)} m max height`);document.querySelector('#physicsOut').innerHTML=`<b>Result</b><br>Range ≈ ${r.toFixed(2)} m<br>Maximum height ≈ ${h.toFixed(2)} m<br>Flight time ≈ ${time.toFixed(2)} s`;}
function assistant(){sheet(`<h3>🤖 Lab Assistant</h3><input id="q" placeholder="Why does the ball come down?"><button class="primary" id="ask">Ask</button><div id="answer" class="answer">Ask me about gravity, circuits, cells, acids or motion.</div>`);document.querySelector('#ask').onclick=()=>{const q=document.querySelector('#q').value.toLowerCase();document.querySelector('#answer').textContent=q.includes('gravity')?'Gravity accelerates the ball downward; in the ideal model the acceleration is g.':q.includes('circuit')?'A complete conducting path allows current to flow; for a resistor I = V/R.':'Change one variable at a time, observe the result, then explain why it happened.';};}
function people(){sheet(`<h3>👥 Lab Team</h3><div class="people">${labPeople.map(p=>`<div><b>${p[0]} ${esc(p[1])}</b><strong>${esc(p[2])}</strong><small>${esc(p[3])}</small></div>`).join('')}</div>`);}
function report(){sheet(`<h3>📊 Lab Report</h3><p>Trials completed: ${results.length}</p><div class="answer">${results.length?results.join('<br>'):'No trials yet.'}</div>`);}
function ui(){document.querySelector('#toolsBtn').onclick=tools;document.querySelector('#assistantBtn').onclick=assistant;document.querySelector('#reportBtn').onclick=report;document.querySelector('#selfBtn').onclick=self;document.querySelector('#peopleBtn').onclick=people;document.querySelector('#expBtn').onclick=()=>document.querySelector('#expList').scrollIntoView({behavior:'smooth'});labs();classes();}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);for(const b of balls){b.t+=dt;const x=b.v*Math.cos(b.a)*b.t,y=.5+b.v*Math.sin(b.a)*b.t-.5*b.g*b.t*b.t;b.o.position.set(x,Math.max(.28,y),0);if(b.t>b.time+.2)b.t=0;}scene.traverse(o=>{if(o.userData?.phase!==undefined)o.rotation.y=Math.sin(clock.elapsedTime*.8+o.userData.phase)*.08;});controls.update();renderer.render(scene,camera);}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
world();ui();perf.textContent='● 3D READY';document.querySelector('#boot').remove();animate();
}catch(e){fail(e);}
