import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { experiments, labPeople, apparatus } from './data.js';
import './style.css';

const app=document.querySelector('#app');
app.innerHTML=`<div id="scene"></div><div class="hud"><header><div class="brand">🧪 <b>Science</b>Verse <small>3D LAB</small></div><div id="perf">● READY</div></header><div class="desktopPanels"><section class="panel"><h4>LABS</h4><button data-lab="chem">🧪 Chemistry</button><button data-lab="phys">⚡ Physics</button><button data-lab="bio">🧬 Biology</button><button data-lab="space">🚀 Space Lab</button><button id="peopleBtn">👥 People</button></section><section class="panel right"><h4>EXPERIMENT</h4><select id="class"></select><div id="expList"></div><button id="selfBtn" class="primary">🧠 Self Experiment</button></section></div><div class="bottom"><button id="expBtn">🧪 Experiments</button><button id="toolsBtn">🧰 Equipment</button><button id="assistantBtn">🤖 Assistant</button><button id="reportBtn">📊 Lab Report</button></div><div id="sheet" class="sheet"></div><div id="joy" class="joy"><i></i></div><div class="look">☝️ Drag = look • 🤏 Pinch = zoom</div></div>`;

const sceneEl=document.querySelector('#scene');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x061018);scene.fog=new THREE.Fog(0x061018,22,55);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.05,120);camera.position.set(10,5.8,12);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;sceneEl.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=4;controls.maxDistance=34;controls.maxPolarAngle=Math.PI*.49;controls.target.set(0,2,0);
const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2();let selected=null, labMode='phys', balls=[], results=[];
const clock=new THREE.Clock();

function material(color,rough=.55,metal=.08){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});}
function box(name,x,y,z,w,h,d,color){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color));o.name=name;o.position.set(x,y,z);scene.add(o);return o;}
function cyl(name,x,y,z,r,h,color){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),material(color,.35));o.name=name;o.position.set(x,y,z);scene.add(o);return o;}
function sphere(name,x,y,z,r,color){const o=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),material(color,.35));o.name=name;o.position.set(x,y,z);scene.add(o);return o;}
function textSprite(text){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#081722';x.roundRect(8,8,496,112,22);x.fill();x.fillStyle='#dff9ff';x.font='bold 38px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,64);const t=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));s.scale.set(3.2,.8,1);return s;}
function buildRoom(){
 scene.add(new THREE.HemisphereLight(0xbfeaff,0x16202a,2.0));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(8,13,7);scene.add(key);
 box('Floor',0,-.25,0,32,.5,24,0x1a252a);box('BackWall',0,5,-11,32,10,.3,0x14252c);box('LeftWall',-16,5,0,.3,10,22,0x122128);box('RightWall',16,5,0,.3,10,22,0x122128);
 for(let x=-12;x<=12;x+=6){box('Bench',x,1.45,-2,5.2,.45,3.3,0x6c7478);box('Shelf',x,3.3,-3.35,4.8,2.3,.22,0x26383f);}
 const stations=[['CHEMISTRY',-9,0x2f6672],['PHYSICS',3,0x4c536d],['BIOLOGY',-3,0x466e58],['SPACE',9,0x5b4d78]];stations.forEach(([label,x,col])=>{const s=textSprite(label);s.position.set(x,5.2,-3.4);scene.add(s);box('station',x,0.15,-7,5,.2,1,col);});
 // Chemistry glassware
 for(let x=-11;x<=-7;x+=2){cyl('beaker',x,2.05,-2,.38,.8,0x72dfff);cyl('flask',x+.7,2.05,-2,.46,.7,0x72d0bd);}
 // Physics apparatus
 box('Track',2,1.93,-2,6,.1,.45,0x3f474d);box('Cart',1,2.3,-2,.9,.5,.75,0xd95252);sphere('wheel',.72,2.03,-2.36,.16,0x17191b);sphere('wheel',1.28,2.03,-2.36,.16,0x17191b);box('Meter',4,2.25,-2,1.1,.65,.55,0x203d4c);
 box('PendulumStand',6,3.3,-2,.15,3.2,.15,0xbcc6ca);sphere('PendulumBob',6,1.9,-2,.34,0xff5368);
 // Biology
 cyl('Microscope',-4.5,2.3,1.8,.45,1.7,0x89969b);cyl('Centrifuge',-2.2,2.0,1.8,.7,.55,0x59686e);box('PCR',-4,2.0,4,1.6,.9,1.1,0x344c55);box('BioBench',-1,1.45,2.8,6,.45,2.5,0x657277);
 // Space bench + rocket
 box('SpaceBench',9,1.45,2.8,6,.45,2.5,0x535b66);cyl('RocketBody',9,3.4,2.8,.45,2.8,0xd9dce0);cyl('RocketNose',9,5.05,2.8,.45,.55,0xff5a62);for(const dx of [-.42,.42])box('Fin',9+dx,2.65,2.8,.18,.7,.75,0xff6b4d);
 // Molecular cluster
 for(let i=0;i<9;i++){const a=i*Math.PI*2/9;const q=sphere('Atom',12+Math.cos(a)*1.3,3.7+Math.sin(a)*.9,3,.25,i%3===0?0xff5b6e:0x56d8ff);q.userData.atom=true;}
 // NPCs, simple animated silhouettes
 labPeople.forEach((p,i)=>makePerson(p[0],p[1],-12+i*4,1.0+i%2*2,2.8));
}
function makePerson(emoji,name,x,z,seed){const g=new THREE.Group();g.position.set(x,0,z);g.userData.name=name;const body=material(seed%2?0x405a78:0x6d4e7e);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.32,.9,4,8),body);torso.position.y=1.15;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.28,12,10),material(0xf1c5a8));head.position.y=1.9;g.add(head);const leg1=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.55,3,6),body);leg1.position.set(-.13,.45,0);g.add(leg1);const leg2=leg1.clone();leg2.position.x=.13;g.add(leg2);g.userData.phase=seed;scene.add(g);const label=textSprite(name);label.scale.set(2,.5,1);label.position.set(0,2.55,0);g.add(label);}
function fillClasses(){const sel=document.querySelector('#class');Object.keys(experiments).forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=k==='12+'?'Class 12+':`Class ${k}`;sel.appendChild(o)});sel.value='12';renderExperiments();}
function renderExperiments(){const list=document.querySelector('#expList');const cls=document.querySelector('#class').value;list.innerHTML=experiments[cls].map((e,i)=>`<button class="exp" data-exp="${e}"><b>${e}</b><small>Guided practical • apparatus • observation • result</small></button>`).join('');list.querySelectorAll('.exp').forEach(b=>b.onclick=()=>openExperiment(b.dataset.exp,cls));}
function openExperiment(name,cls){openSheet(`<h3>🧪 ${name}</h3><p>Class ${cls}. Perform this as a simulation rather than memorising steps.</p><div class="steps"><b>1. Aim</b><span>Explore ${name} and identify the variables.</span><b>2. Apparatus</b><span>Choose the required equipment from the workbench.</span><b>3. Perform</b><span>Move, place, connect or measure objects yourself.</span><b>4. Observe</b><span>Record live readings and compare trials.</span><b>5. Result</b><span>Generate a lab record from your observations.</span></div><button class="primary" id="startExp">▶ Enter Experiment</button>`);document.querySelector('#startExp').onclick=()=>{closeSheet();document.querySelector('#current').textContent=`${name} • Class ${cls} • interactive mode`;teleport(name.toLowerCase().includes('projectile')?'phys':name.toLowerCase().includes('pcr')?'bio':name.toLowerCase().includes('rocket')?'space':'chem');};}
function openSheet(html){const s=document.querySelector('#sheet');s.innerHTML=`<div class="sheetHead"><button id="close">✕</button></div>${html}`;s.classList.add('open');document.querySelector('#close').onclick=closeSheet;}
function closeSheet(){document.querySelector('#sheet').classList.remove('open');}
function tools(){openSheet(`<h3>🧰 Equipment Locker</h3><div class="toolgrid">${apparatus.map(a=>`<button data-tool="${a}">${a}</button>`).join('')}</div><p class="muted">Tap equipment to bring it to your workbench. The physics sandbox uses the same world and state.</p>`);document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>spawn(b.dataset.tool));}
function spawn(type){const t=type.toLowerCase();let o;if(t.includes('ball'))o=sphere('UserBall',0,3,-1,.32,0xff4f64);else if(t.includes('battery')){o=box('Battery',0,2.5,-1,.7,.8,.7,0x202b35);box('BatteryTerminal',-.18,2.95,-1,.12,.08,.12,0xff5a5a);box('BatteryTerminal',.18,2.95,-1,.12,.08,.12,0x55baff);}else if(t.includes('beaker'))o=cyl('UserBeaker',0,2.25,-1,.4,.8,0x65dfff);else if(t.includes('burette')){o=cyl('Burette',0,3,-1,.08,2.2,0x8ce8ff);box('BuretteStand',.35,2.4,-1,.08,1.9,.08,0xb9c0c4);}else o=box(type,0,2.4,-1,.8,.8,.8,0x718087);o.userData.interactive=true;selected=o;closeSheet();document.querySelector('#current').textContent=`${type} placed in your workbench.`;}
function throwBall(){const speed=+document.querySelector('#speed').value,angle=+document.querySelector('#angle').value*Math.PI/180,g=+document.querySelector('#gravity').value;const h=.5;const range=speed*speed*Math.sin(2*angle)/g,maxH=h+speed*speed*Math.sin(angle)**2/(2*g),time=2*speed*Math.sin(angle)/g;const ball=sphere('ThrownBall',0,h,0,.28,0xff465e);balls.push({mesh:ball,t:0,speed,angle,g,time});document.querySelector('#physicsOut').innerHTML=`<b>Live model</b><br>v₀ = ${speed.toFixed(1)} m/s<br>angle = ${(angle*180/Math.PI).toFixed(0)}°<br>gravity = ${g.toFixed(2)} m/s²<br>maximum height ≈ ${maxH.toFixed(2)} m<br>range ≈ ${range.toFixed(2)} m<br>flight time ≈ ${time.toFixed(2)} s`;results.push(`Projectile: ${range.toFixed(2)} m range, ${maxH.toFixed(2)} m max height`);}
function assistant(){openSheet(`<h3>🤖 Lab Assistant</h3><p>Hi! I work inside the lab. Ask me a science question.</p><input id="q" placeholder="Why does the ball come down?"><button class="primary" id="ask">Ask</button><div id="answer" class="answer">Try asking about gravity, force, circuits, acids, cells or an experiment.</div>`);document.querySelector('#ask').onclick=()=>{const q=document.querySelector('#q').value.toLowerCase();let a=q.includes('gravity')?'Gravity accelerates the ball downward. In the ideal model, acceleration is g, so vertical velocity changes by g×time.':q.includes('circuit')?'A complete conducting path lets current flow. For a simple resistor, Ohm’s law is I = V/R.':q.includes('cell')?'Cells contain organised structures with specialised jobs; use the Biology Lab to inspect a model.':'Change one variable at a time, observe the result, and explain the result using the scientific model.';document.querySelector('#answer').textContent=a;};}
function report(){openSheet(`<h3>📊 Lab Report</h3><p>Trials completed: ${results.length}</p><div class="answer">${results.length?results.join('<br>'):'No trials yet. Run an experiment first.'}</div><button class="primary" onclick="window.print()">Print / Save report</button>`);}
function people(){openSheet(`<h3>👥 People in the Lab</h3><div class="people">${labPeople.map(p=>`<div><b>${p[0]} ${p[1]}</b><strong>${p[2]}</strong><small>${p[3]}</small></div>`).join('')}</div>`);}
function teleport(where){const pos={chem:[-9,4,8],phys:[3,4,8],bio:[-3,4,10],space:[9,4,10]};const p=pos[where]||pos.chem;controls.target.set(...p);camera.position.set(p[0]+7,p[1]+2,p[2]+7);closeSheet();}
function bind(){document.querySelector('#class').onchange=renderExperiments;document.querySelector('#selfBtn').onclick=()=>openSheet(`<h3>🧠 Self Experiment</h3><p>Use the world without a fixed recipe. Start with projectile motion, then add your own variables.</p><label>Speed <output id="so">12</output> m/s</label><input id="speed" type="range" min="1" max="30" value="12"><label>Angle <output id="ao">45</output>°</label><input id="angle" type="range" min="5" max="85" value="45"><label>Gravity <output id="go">9.81</output> m/s²</label><input id="gravity" type="range" min="1" max="20" step=".01" value="9.81"><button class="primary" id="throw">🔴 Throw Ball</button><div id="physicsOut" class="answer">Change variables and throw.</div>`);document.querySelector('#throw').onclick=throwBall;document.querySelector('#speed').oninput=e=>document.querySelector('#so').value=e.target.value;document.querySelector('#angle').oninput=e=>document.querySelector('#ao').value=e.target.value;document.querySelector('#gravity').oninput=e=>document.querySelector('#go').value=e.target.value;document.querySelector('#expBtn').onclick=()=>openSheet(`<h3>🧪 Experiment Library</h3><select id="sheetClass">${Object.keys(experiments).map(k=>`<option>${k}</option>`).join('')}</select><div id="sheetExps"></div>`);document.querySelector('#toolsBtn').onclick=tools;document.querySelector('#assistantBtn').onclick=assistant;document.querySelector('#reportBtn').onclick=report;document.querySelector('#peopleBtn').onclick=people;document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>teleport(b.dataset.lab));document.querySelector('#sheet')?.addEventListener('change',e=>{if(e.target.id==='sheetClass'){const c=e.target.value;document.querySelector('#sheetExps').innerHTML=experiments[c].map(x=>`<button class="exp" onclick="this.nextElementSibling?.click()"><b>${x}</b></button>`).join('')}});}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.033);controls.update();balls.forEach((b,i)=>{b.t+=dt;const x=b.speed*Math.cos(b.angle)*b.t,z=-b.speed*Math.cos(b.angle)*b.t*.18,y=.5+b.speed*Math.sin(b.angle)*b.t-.5*b.g*b.t*b.t;b.mesh.position.set(x,y,z);if(y<.28){b.mesh.position.y=.28;b.t+=.03;if(b.t>b.time+.7){scene.remove(b.mesh);balls.splice(i,1);}}});scene.traverse(o=>{if(o.userData.phase!==undefined){o.position.x+=Math.sin(performance.now()/900+o.userData.phase)*.001;}});renderer.render(scene,camera);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));});
renderer.domElement.addEventListener('pointerdown',e=>{pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(scene.children,true);const hit=hits.find(h=>h.object.userData.interactive||h.object.name==='UserBall');if(hit){selected=hit.object;document.querySelector('#perf').textContent=`● ${selected.name}`;}});
// Mobile joystick: move the camera target so the lab feels navigable without a desktop keyboard.
const joy=document.querySelector('#joy'),stick=joy.querySelector('i');let dragging=false;joy.addEventListener('pointerdown',e=>{dragging=true;joy.setPointerCapture(e.pointerId)});joy.addEventListener('pointermove',e=>{if(!dragging)return;const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=(e.clientX-cx)/(r.width/2),dy=(e.clientY-cy)/(r.height/2);const l=Math.hypot(dx,dy);if(l>1){dx/=l;dy/=l}stick.style.transform=`translate(${dx*25}px,${dy*25}px)`;controls.target.x+=dx*.12;controls.target.z+=dy*.12;camera.position.x+=dx*.12;camera.position.z+=dy*.12});joy.addEventListener('pointerup',()=>{dragging=false;stick.style.transform=''});
try{buildRoom();fillClasses();bind();document.querySelector('#boot').remove();}catch(e){console.error(e);document.querySelector('#boot').style.display='none';document.querySelector('#fallback').style.display='grid';}
